[[testcases]]
day = 1
part = 1
solution = "11"
input = '''
3   4
4   3
2   5
1   3
3   9
3   3
'''

[[testcases]]
day = 1
part = 2
solution = "31"
input = '''
3   4
4   3
2   5
1   3
3   9
3   3
'''

[[testcases]]
day = 2
part = 1
solution = "2"
input = '''
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
'''

[[testcases]]
day = 2
part = 2
solution = "4"
input = '''
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
'''

[[testcases]]
day = 3
part = 1
solution = "161"
input = '''
xmul(2,4)%&mul[3,7]!@^do_not_mul(5,5)+mul(32,64]then(mul(11,8)mul(8,5))
'''

[[testcases]]
day = 3
part = 2
solution = "48"
input = '''
xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))
'''

[[testcases]]
day = 4
part = 1
solution = "18"
input = '''
MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX
'''

[[testcases]]
day = 4
part = 2
solution = "9"
input = '''
.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........
'''

[[testcases]]
day = 5
part = 1
solution = "143"
input = '''
47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47
'''

[[testcases]]
day = 5
part = 2
solution = "123"
input = '''
47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47
'''

[[testcases]]
day = 6
part = 1
solution = "41"
input = '''
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
'''

[[testcases]]
day = 6
part = 2
solution = "6"
input = '''
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
'''

[[testcases]]
day = 7
part = 1
solution = "3749"
input = '''
190: 10 19
3267: 81 40 27
83: 17 5
156: 15 6
7290: 6 8 6 15
161011: 16 10 13
192: 17 8 14
21037: 9 7 18 13
292: 11 6 16 20
'''

[[testcases]]
day = 7
part = 2
solution = "11387"
input = '''
190: 10 19
3267: 81 40 27
83: 17 5
156: 15 6
7290: 6 8 6 15
161011: 16 10 13
192: 17 8 14
21037: 9 7 18 13
292: 11 6 16 20
'''

[[testcases]]
day = 8
part = 1
solution = "14"
input = '''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
'''

[[testcases]]
day = 8
part = 2
solution = "34"
input = '''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
'''

[[testcases]]
day = 9
part = 1
solution = "1928"
input = '''
2333133121414131402
'''

[[testcases]]
day = 9
part = 2
solution = "2858"
input = '''
2333133121414131402
'''

[[testcases]]
day = 10
part = 1
example_no = 1
solution = "1"
input = '''
0123
1234
8765
9876
'''
[[testcases]]
day = 10
part = 1
example_no = 2
solution = "2"
input = '''
...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
'''
[[testcases]]
day = 10
part = 1
example_no = 3
solution = "4"
input = '''
..90..9
...1.98
...2..7
6543456
765.987
876....
987....
'''
[[testcases]]
day = 10
part = 1
example_no = 4
solution = "36"
input = '''
89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
'''

[[testcases]]
day = 10
part = 2
example_no = 1
solution = "3"
input = '''
.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
'''

[[testcases]]
day = 10
part = 2
example_no = 2
solution = "13"
input = '''
..90..9
...1.98
...2..7
6543456
765.987
876....
987....
'''

[[testcases]]
day = 10
part = 2
example_no = 3
solution = "227"
input = '''
012345
123456
234567
345678
4.6789
56789.
'''

[[testcases]]
day = 10
part = 2
example_no = 4
solution = "81"
input = '''
89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
'''

[[testcases]]
day = 11
part = 1
solution = "55312"
input = '''
125 17
'''

[[testcases]]
day = 11
part = 2
note = "No testcase given - using my own result."
solution = "65601038650482"
input = '''
125 17
'''

[[testcases]]
day = 12
part = 1
solution = "140"
input = '''
AAAA
BBCD
BBCC
EEEC
'''

[[testcases]]
day = 12
part = 2
example_no = 1
solution = "80"
input = '''
AAAA
BBCD
BBCC
EEEC
'''

[[testcases]]
day = 12
part = 2
example_no = 2
solution = "236"
input = '''
EEEEE
EXXXX
EEEEE
EXXXX
EEEEE
'''

[[testcases]]
day = 12
part = 2
example_no = 3
solution = "368"
input = '''
AAAAAA
AAABBA
AAABBA
ABBAAA
ABBAAA
AAAAAA
'''

[[testcases]]
day = 12
part = 2
example_no = 4
solution = "1206"
input = '''
RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE
'''

[[testcases]]
day = 13
part = 1
solution = "480"
input = '''
Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279
'''

[[testcases]]
day = 13
part = 2
solution = "875318608908"
input = '''
Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400

Button A: X+26, Y+66
Button B: X+67, Y+21
Prize: X=12748, Y=12176

Button A: X+17, Y+86
Button B: X+84, Y+37
Prize: X=7870, Y=6450

Button A: X+69, Y+23
Button B: X+27, Y+71
Prize: X=18641, Y=10279
'''

[[testcases]]
day = 14
part = 1
solution = "12"
arg = "IVec2::new(11, 7)"
input = '''
p=0,4 v=3,-3
p=6,3 v=-1,-3
p=10,3 v=-1,2
p=2,0 v=2,-1
p=0,0 v=1,3
p=3,0 v=-2,-2
p=7,6 v=-1,-3
p=3,0 v=-1,-2
p=9,3 v=2,3
p=7,3 v=-1,2
p=2,4 v=2,-3
p=9,5 v=-3,-3
'''

[[testcases]]
day = 15
part = 1
example_no = 1
solution = "2028"
input = '''
########
#..O.O.#
##@.O..#
#...O..#
#.#.O..#
#...O..#
#......#
########

<^^>>>vv
<v>>v<<
'''

[[testcases]]
day = 15
part = 1
example_no = 2
solution = "10092"
input = '''
##########
#..O..O.O#
#......O.#
#.OO..O.O#
#..O@..O.#
#O#..O...#
#O..O..O.#
#.OO.O.OO#
#....O...#
##########

<vv>^<v^>v>^vv^v>v<>v^v<v<^vv<<<^><<><>>v<vvv<>^v^>^<<<><<v<<<v^vv^v>^
vvv<<^>^v^^><<>>><>^<<><^vv^^<>vvv<>><^^v>^>vv<>v<<<<v<^v>^<^^>>>^<v<v
><>vv>v^v^<>><>>>><^^>vv>v<^^^>>v^v^<^^>v^^>v^<^v>v<>>v^v^<v>v^^<^^vv<
<<v<^>>^^^^>>>v^<>vvv^><v<<<>^^^vv^<vvv>^>v<^^^^v<>^>vvvv><>>v^<<^^^^^
^><^><>>><>^^<<^^v>>><^<v>^<vv>>v>>>^v><>^v><<<<v>>v<v<v>vvv>^<><<>^><
^>><>^v<><^vvv<^^<><v<<<<<><^v<<<><<<^^<v<^^^><^>>^<v^><<<^>>^v<v^v<v^
>^>>^v>vv>^<<^v<>><<><<v<<v><>v<^vv<<<>^^v^>^^>>><<^v>>v^v><^^>>^<>vv^
<><^^>^^^<><vvvvv^v<v<<>^v<v>v<<^><<><<><<<^^<<<^<<>><<><^^^>^^<>^>v<>
^^>vv<^v^v<vv>^<><v<^v>^^^>>>^^vvv^>vvv<>>>^<^>>>>>^<<^v>^vvv<>^<><<v>
v^^>>><<^^<>>^v^<v^vv<>v^<<>^<^v^v><^<<<><<^<v><v<>vv>>v><v^<vv<>v^<<^
'''

[[testcases]]
day = 15
part = 2
solution = "9021"
input = '''
##########
#..O..O.O#
#......O.#
#.OO..O.O#
#..O@..O.#
#O#..O...#
#O..O..O.#
#.OO.O.OO#
#....O...#
##########

<vv>^<v^>v>^vv^v>v<>v^v<v<^vv<<<^><<><>>v<vvv<>^v^>^<<<><<v<<<v^vv^v>^
vvv<<^>^v^^><<>>><>^<<><^vv^^<>vvv<>><^^v>^>vv<>v<<<<v<^v>^<^^>>>^<v<v
><>vv>v^v^<>><>>>><^^>vv>v<^^^>>v^v^<^^>v^^>v^<^v>v<>>v^v^<v>v^^<^^vv<
<<v<^>>^^^^>>>v^<>vvv^><v<<<>^^^vv^<vvv>^>v<^^^^v<>^>vvvv><>>v^<<^^^^^
^><^><>>><>^^<<^^v>>><^<v>^<vv>>v>>>^v><>^v><<<<v>>v<v<v>vvv>^<><<>^><
^>><>^v<><^vvv<^^<><v<<<<<><^v<<<><<<^^<v<^^^><^>>^<v^><<<^>>^v<v^v<v^
>^>>^v>vv>^<<^v<>><<><<v<<v><>v<^vv<<<>^^v^>^^>>><<^v>>v^v><^^>>^<>vv^
<><^^>^^^<><vvvvv^v<v<<>^v<v>v<<^><<><<><<<^^<<<^<<>><<><^^^>^^<>^>v<>
^^>vv<^v^v<vv>^<><v<^v>^^^>>>^^vvv^>vvv<>>>^<^>>>>>^<<^v>^vvv<>^<><<v>
v^^>>><<^^<>>^v^<v^vv<>v^<<>^<^v^v><^<<<><<^<v><v<>vv>>v><v^<vv<>v^<<^
'''

[[testcases]]
day = 16
part = 1
solution = "7036"
input = '''
###############
#.......#....E#
#.#.###.#.###.#
#.....#.#...#.#
#.###.#####.#.#
#.#.#.......#.#
#.#.#####.###.#
#...........#.#
###.#.#####.#.#
#...#.....#.#.#
#.#.#.###.#.#.#
#.....#...#.#.#
#.###.#.#.#.#.#
#S..#.....#...#
###############
'''

[[testcases]]
day = 16
part = 2
solution = "45"
input = '''
###############
#.......#....E#
#.#.###.#.###.#
#.....#.#...#.#
#.###.#####.#.#
#.#.#.......#.#
#.#.#####.###.#
#...........#.#
###.#.#####.#.#
#...#.....#.#.#
#.#.#.###.#.#.#
#.....#...#.#.#
#.###.#.#.#.#.#
#S..#.....#...#
###############
'''

[[testcases]]
day = 17
part = 1
solution = "4,6,3,5,6,3,5,2,1,0"
input = '''
Register A: 729
Register B: 0
Register C: 0

Program: 0,1,5,4,3,0
'''

[[testcases]]
day = 17
part = 2
solution = "117440"
input = '''
Register A: 0
Register B: 0
Register C: 0

Program: 0,3,5,4,3,0
'''

[[testcases]]
day = 18
part = 1
solution = "22"
input = '''
5,4
4,2
4,5
3,0
2,1
6,3
2,4
1,5
0,6
3,3
2,6
5,1
1,2
5,5
2,5
6,5
1,4
0,4
6,4
1,1
6,1
1,0
0,5
1,6
2,0
'''

[[testcases]]
day = 18
part = 2
solution = "6,1"
input = '''
5,4
4,2
4,5
3,0
2,1
6,3
2,4
1,5
0,6
3,3
2,6
5,1
1,2
5,5
2,5
6,5
1,4
0,4
6,4
1,1
6,1
1,0
0,5
1,6
2,0
'''

[[testcases]]
day = 19
part = 1
solution = "6"
input = '''
r, wr, b, g, bwu, rb, gb, br

brwrr
bggr
gbbr
rrbgbr
ubwu
bwurrg
brgr
bbrgwb
'''

[[testcases]]
day = 19
part = 2
solution = "16"
input = '''
r, wr, b, g, bwu, rb, gb, br

brwrr
bggr
gbbr
rrbgbr
ubwu
bwurrg
brgr
bbrgwb
'''

[[testcases]]
day = 20
part = 1
arg = "None"
solution = "45"
input = '''
###############
#...#...#.....#
#.#.#.#.#.###.#
#S#...#.#.#...#
#######.#.#.###
#######.#.#...#
#######.#.###.#
###..E#...#...#
###.#######.###
#...###...#...#
#.#####.#.###.#
#.#...#.#.#...#
#.#.#.#.#.#.###
#...#...#...###
###############
'''

[[testcases]]
day = 20
part = 2
arg = "50"
solution = "45"
input = '''
###############
#...#...#.....#
#.#.#.#.#.###.#
#S#...#.#.#...#
#######.#.#.###
#######.#.#...#
#######.#.###.#
###..E#...#...#
###.#######.###
#...###...#...#
#.#####.#.###.#
#.#...#.#.#...#
#.#.#.#.#.#.###
#...#...#...###
###############
'''

[[testcases]]
day = 21
part = 1
solution = "126384"
input = '''
029A
980A
179A
456A
379A
'''

[[testcases]]
day = 21
part = 2
solution = "154115708116294"
input = '''
029A
980A
179A
456A
379A
'''

[[testcases]]
day = 22
part = 1
solution = "37327623"
input = '''
1
10
100
2024
'''

[[testcases]]
day = 22
part = 2
solution = "23"
input = '''
1
2
3
2024
'''

[[testcases]]
day = 23
part = 1
solution = "7"
input = '''
kh-tc
qp-kh
de-cg
ka-co
yn-aq
qp-ub
cg-tb
vc-aq
tb-ka
wh-tc
yn-cg
kh-ub
ta-co
de-co
tc-td
tb-wq
wh-td
ta-ka
td-qp
aq-cg
wq-ub
ub-vc
de-ta
wq-aq
wq-vc
wh-yn
ka-de
kh-ta
co-tc
wh-qp
tb-vc
td-yn

'''

[[testcases]]
day = 23
part = 2
solution = "co,de,ka,ta"
input = '''
kh-tc
qp-kh
de-cg
ka-co
yn-aq
qp-ub
cg-tb
vc-aq
tb-ka
wh-tc
yn-cg
kh-ub
ta-co
de-co
tc-td
tb-wq
wh-td
ta-ka
td-qp
aq-cg
wq-ub
ub-vc
de-ta
wq-aq
wq-vc
wh-yn
ka-de
kh-ta
co-tc
wh-qp
tb-vc
td-yn
'''

[[testcases]]
day = 24
part = 1
solution = "2024"
input = '''
x00: 1
x01: 0
x02: 1
x03: 1
x04: 0
y00: 1
y01: 1
y02: 1
y03: 1
y04: 1

ntg XOR fgs -> mjb
y02 OR x01 -> tnw
kwq OR kpj -> z05
x00 OR x03 -> fst
tgd XOR rvg -> z01
vdt OR tnw -> bfw
bfw AND frj -> z10
ffh OR nrd -> bqk
y00 AND y03 -> djm
y03 OR y00 -> psh
bqk OR frj -> z08
tnw OR fst -> frj
gnj AND tgd -> z11
bfw XOR mjb -> z00
x03 OR x00 -> vdt
gnj AND wpb -> z02
x04 AND y00 -> kjc
djm OR pbm -> qhw
nrd AND vdt -> hwm
kjc AND fst -> rvg
y04 OR y02 -> fgs
y01 AND x02 -> pbm
ntg OR kjc -> kwq
psh XOR fgs -> tgd
qhw XOR tgd -> z09
pbm OR djm -> kpj
x03 XOR y03 -> ffh
x00 XOR y04 -> ntg
bfw OR bqk -> z06
nrd XOR fgs -> wpb
frj XOR qhw -> z04
bqk OR frj -> z07
y03 OR x01 -> nrd
hwm AND bqk -> z03
tgd XOR rvg -> z12
tnw OR pbm -> gnj
'''


[[testcases]]
day = 25
part = 1
solution = "3"
input = '''
#####
.####
.####
.####
.#.#.
.#...
.....

#####
##.##
.#.##
...##
...#.
...#.
.....

.....
#....
#....
#...#
#.#.#
#.###
#####

.....
.....
#.#..
###..
###.#
###.#
#####

.....
.....
.....
#....
#.#..
#.#.#
#####

'''

